### ISSUE TITLE
error "command not found" due to return code in double quotes

### ISSUE THREAD

**Issue by zerobikappa** [linuxdeploy/linuxdeploy-plugin-gstreamer#11]
error due to place the return code in double quotes

https://github.com/linuxdeploy/linuxdeploy-plugin-gstreamer/blob/f7881a481616bb6f0c648a946747fda9de0f5275/linuxdeploy-plugin-gstreamer.sh#L110

https://github.com/linuxdeploy/linuxdeploy-plugin-gstreamer/blob/f7881a481616bb6f0c648a946747fda9de0f5275/linuxdeploy-plugin-gstreamer.sh#L130

should be
```bash
$(file "$i" | grep -v ELF --silent) && echo "Ignoring non ELF file: $i" && continue
```

**Comment by TheAssassin** [comment]
Actually, it should be `(file "$i" | grep -v ELF --silent) && echo "Ignoring non ELF file: $i" && continue`. The leading `$` will capture the subshell's output into a string, that's why it doesn't work.

Please send a PR.

**Comment by zerobikappa** [comment]
after I submitted PR, I found someone already did the same thing(https://github.com/linuxdeploy/linuxdeploy-plugin-gstreamer/pull/6) 1 year ago. but the PR was still pending in queue till now...

**Comment by zerobikappa** [comment]
#13
