### ISSUE TITLE
Script does not work in Arch Linux!

### ISSUE THREAD

**Issue by namanlp** [linuxdeploy/linuxdeploy-plugin-gstreamer#18]
Hi there!

Actually, in Arch Linux, the Gstreamer directory is `/usr/lib/gstreamer-1.0` instead of `/usr/lib/x86_64-linux-gnu/gstreamer-1.0` , unlike Debian Based distributions.

So, the script fails on the non-Debian distributions due to Gstreamer not found issue.

**Comment by TheAssassin** [comment]
Looks good to me.
