### ISSUE TITLE
rpath is missing

### ISSUE THREAD

**Issue by Stivius** [linuxdeploy/linuxdeploy-plugin-gstreamer#2]
When I'm running linuxdeploy on usual libraries the rpath is set to all of them. However, gstreamer plugins are just copied to the folder without any modification. Due to this I'm getting the following errors while running:
```
(gst-plugin-scanner:44952): GStreamer-WARNING **: 01:09:14.987: Failed to load plugin '/tmp/.mount_Xibo_Pq9LncK/usr/lib/gstreamer-1.0/libgstcdio.so': libcdio.so.17: cannot open shared object file: No such file or directory

(gst-plugin-scanner:44962): GStreamer-WARNING **: 01:09:15.089: Failed to load plugin '/tmp/.mount_Xibo_Pq9LncK/usr/lib/gstreamer-1.0/libgstdvdread.so': libdvdread.so.4: cannot open shared object file: No such file or directory
```
I've fixed it by adding LD_LIBRARY_PATH=${APPDIR}/usr/lib in apprun-hooks script but I suppose setting rpath is better because this approach is chosen in the linuxdeploy.

**Comment by TheAssassin** [comment]
_Should_ be fixed since https://github.com/linuxdeploy/linuxdeploy-plugin-gstreamer/pull/3. Can you please retry?
